"""Route reason code constants."""

SEMANTIC_CACHE_HIT          = "semantic_cache_hit"
SIMPLE_TASK_CHEAPEST        = "simple_task_cheapest_model"
REASONING_TASK_BALANCED     = "reasoning_task_balanced_model"
JSON_EXTRACT_JSON_CAPABLE   = "json_extract_json_capable_model"
BEST_QUALITY_FORCED         = "best_quality_forced_large_model"
CHEAP_QUALITY_FORCED        = "cheap_quality_forced_small_model"
FALLBACK_SECONDARY_PROVIDER = "fallback_to_secondary_provider"
PROVIDER_GENERATION_FAILED  = "provider_generation_failed"
VALIDATION_FAILED           = "validation_failed"
NO_SUITABLE_MODEL           = "no_suitable_model_found"
TOKEN_LIMIT_EXCEEDED        = "input_exceeds_all_context_windows"
